export const seedPayload = {
  profile: {
    displayName: 'Md. Tofayel Islam',
    shortName: 'Tofayel',
    handle: 'YEL-59',
    role: 'Frontend Developer',
    avatarUrl: '/tofayel.png',
    avatarInitial: 'T',
    email: 'tofayeltuhin143@gmail.com',
    phone: '+8801708901418',
    website: 'https://tofayel.vercel.app',
    collectionLabel: 'Development',
    availabilityStatus: 'Open to freelance',
    yearsExperience: '2+ years',
    seoTitle: 'Md. Tofayel Islam — Frontend Developer',
    seoDescription:
      'Frontend developer building React & Next.js interfaces from Dhaka, Bangladesh.',
    bioParagraphs: [
      "I'm Md. Tofayel Islam — a frontend developer with 2+ years building React & Next.js apps. I grew up in Peelkhana, Dhaka, studied at BMARPC & Rifles Public College, and graduated from Daffodil International University with a BSc in Computer Science & Engineering.",
      'Currently at Softvence, I ship responsive, conversion-focused interfaces. I love AI-powered products, design systems, and sharing tiny open-source components for the community.',
    ],
    locationArea: 'Hatirjheel, Noyatola',
    locationCity: 'Dhaka, Bangladesh',
    lat: 23.8103,
    lng: 90.4125,
    greeting: "Hello, it's Tofayel",
    vaultOriginTitle: 'Origin File',
    vaultOriginDetail:
      'Raised in Peelkhana, Dhaka. Curiosity for computers turned into a career building interfaces.',
    vaultCurrentTitle: 'Current Status',
    vaultCurrentDetail:
      'Frontend Developer at Softvence — React, Next.js, Tailwind. Open to freelance.',
    codeCardStack: ['React', 'Next.js', 'TypeScript', 'Tailwind'],
  },
  resume: {
    pageTitle: 'ATS Resume',
    pageSubtitle:
      'Md. Tofayel Islam — plain-text optimized for applicant tracking systems.',
    accent: '#8b5cf6',
    summary: [
      'Frontend Developer with 2+ years of experience building scalable web applications using React, Next.js, TypeScript, Redux, Tailwind CSS, ShadCN UI.',
      'Strong background in state management, API integration, and responsive design.',
      'Hands-on experience with AI-powered projects including resume generation, cover letter writing, and goal tracking platforms.',
    ],
    skillGroups: [
      {
        group: 'Languages',
        items: 'JavaScript, TypeScript, HTML, CSS',
      },
      {
        group: 'Frameworks',
        items: 'React, Next.js, Redux Toolkit, React Query, Tailwind CSS, ShadCN',
      },
      {
        group: 'Tools',
        items: 'Git, GitHub, VS Code, Figma, Chart.js',
      },
      {
        group: 'Other',
        items: 'REST APIs, Responsive Design, Performance Optimization',
      },
    ],
    codingProfiles: [
      { label: 'LeetCode', href: 'https://leetcode.com' },
      { label: 'HackerRank', href: 'https://hackerrank.com' },
      { label: 'Beecrowd', href: 'https://beecrowd.com' },
    ],
    pdfUrl: '/resume/tofayel-resume.pdf',
    texUrl: '/resume/resume-ats.tex',
    latexRepoUrl: 'https://github.com/YEL-59/Resumelatex',
  },
  about: {
    pageTitle: 'More about me',
    pageSubtitle:
      'Md. Tofayel Islam — frontend developer, CSE graduate, and someone who treats UI like a love letter to the user.',
    accent: '#f472b6',
    introParagraphs: [
      "I'm Md. Tofayel Islam — a frontend developer with 2+ years building React & Next.js apps. I grew up in Peelkhana, Dhaka, studied at BMARPC & Rifles Public College, and graduated from Daffodil International University with a BSc in Computer Science & Engineering.",
      'Currently at Softvence, I ship responsive, conversion-focused interfaces. I love AI-powered products, design systems, and sharing tiny open-source components for the community.',
    ],
    photoUrl: '/tofayel.png',
    handleBadge: 'YEL-59',
    funFacts: [
      { emoji: 'FiHome', label: 'Roots', value: 'Peelkhana, Dhaka' },
      { emoji: 'MdSchool', label: 'Degree', value: 'BSc CSE — DIU' },
      { emoji: 'FiBriefcase', label: 'Now', value: 'Softvence · Frontend' },
      { emoji: 'FiCoffee', label: 'Vibe', value: 'Coffee + clean UI' },
    ],
    philosophies: [
      'Ship interfaces that feel obvious the first time you use them.',
      "TypeScript everywhere — types are documentation you can't skip.",
      'Small components, big impact. Open source what helps the community.',
      'Dhaka-built discipline, global-quality craft.',
    ],
  },
  siteSettings: {
    footerLinks: [
      { label: 'Email', href: 'mailto:hello@tofayel.dev' },
      { label: 'Instagram', href: '#' },
      { label: 'LinkedIn', href: 'https://www.linkedin.com/in/tofayel-islam' },
      { label: 'Github', href: 'https://github.com/YEL-59' },
      { label: 'Medium', href: '#' },
    ],
    brandValues: ['Clarity', 'Utility', 'Empathy', 'Craft'],
    marqueeTrackA: [
      'React',
      'Next.js',
      'TypeScript',
      'Tailwind',
      'UI Systems',
      'Open Source',
    ],
    marqueeTrackB: [
      'Dhaka',
      'Softvence',
      'YEL-59',
      'Frontend',
      'Craft',
      'Ship Fast',
    ],
    availabilityBadge: 'Open to freelance',
    ambientTagline: 'Building interfaces that convert',
    copyrightText: '© 2026 Tofayel. All rights reserved.',
    githubUsername: 'YEL-59',
    timezone: 'Asia/Dhaka',
    vaultMasterPasscode: '1234',
    repoUnlockPassword: 'yel59-repos',
    repoUnlockTtlSeconds: 60,
    vaultHelpSteps: [
      {
        icon: 'FiRefreshCw',
        label: 'Roulette',
        text: 'Spin until the digits align.',
      },
      {
        icon: 'LuSparkles',
        label: 'Seance',
        text: 'Hold focus until the vault opens.',
      },
      {
        icon: 'SiReact',
        label: 'Quantum',
        text: 'Collapse the superposition of digits.',
      },
    ],
    mapInviteLine: "If you're in Dhaka, let's grab a coffee.",
    mapFooterLine: 'Based in Hatirjheel, Noyatola — Dhaka, Bangladesh.',
  },
  skills: [
    { label: 'React', color: '#60a5fa', sortOrder: 1 },
    { label: 'Next.js', color: '#a1a1aa', sortOrder: 2 },
    { label: 'TypeScript', color: '#818cf8', sortOrder: 3 },
    { label: 'Tailwind CSS', color: '#22d3ee', sortOrder: 4 },
    { label: 'JavaScript', color: '#fbbf24', sortOrder: 5 },
    { label: 'GSAP', color: '#34d399', sortOrder: 6 },
    { label: 'Three.js', color: '#a78bfa', sortOrder: 7 },
    { label: 'UI Development', color: '#f472b6', sortOrder: 8 },
    { label: 'Responsive Design', color: '#fb923c', sortOrder: 9 },
    { label: 'Git & GitHub', color: '#94a3b8', sortOrder: 10 },
    { label: 'REST APIs', color: '#2dd4bf', sortOrder: 11 },
    { label: 'Performance', color: '#f87171', sortOrder: 12 },
  ],
  experiences: [
    {
      company: 'Softvence',
      role: 'Frontend Developer',
      employmentType: 'Full-Time',
      location: 'Dhaka',
      startDate: '2024',
      endDate: 'Present',
      yearLabel: '2024 — Now',
      bullets: [
        'Ship responsive, conversion-focused React & Next.js interfaces',
        'Build reusable UI systems and client dashboards',
      ],
      sortOrder: 1,
    },
    {
      company: 'Amromed',
      role: 'Frontend Developer',
      employmentType: 'Full-Time',
      location: 'Dhaka',
      startDate: '2023',
      endDate: '2024',
      yearLabel: '2023 — 2024',
      bullets: [
        'Developed production React applications',
        'Collaborated on design-to-code workflows',
      ],
      sortOrder: 2,
    },
    {
      company: 'Freelance',
      role: 'Frontend Developer — React & Next.js',
      startDate: '2024',
      endDate: 'Present',
      yearLabel: '2024 — Now',
      bullets: [],
      sortOrder: 3,
    },
  ],
  education: [
    {
      year: 'Early',
      place: 'Peelkhana, Dhaka',
      title: 'Where it started',
      detail: 'Raised in Peelkhana — streets, stories, and curiosity.',
      sortOrder: 1,
    },
    {
      year: 'School',
      place: 'BMARPC',
      title: 'School & College',
      detail: 'Built discipline and the first love for computers.',
      sortOrder: 2,
    },
    {
      year: 'College',
      place: 'Rifles Public College',
      title: 'Higher secondary',
      detail: 'Science background, problem-solving mindset.',
      sortOrder: 3,
    },
    {
      year: '2020 — Now',
      place: 'Daffodil International University',
      title: 'BSc in CSE',
      detail: 'Computer Science & Engineering — algorithms to interfaces.',
      location: 'Savar, Dhaka',
      startDate: 'Aug 2018',
      endDate: 'Dec 2023',
      sortOrder: 4,
    },
    {
      year: 'Today',
      place: 'Softvence · Dhaka',
      title: 'Frontend Developer',
      detail: 'React, Next.js, Tailwind — shipping UI that converts.',
      sortOrder: 5,
    },
  ],
  projects: [
    {
      slug: 'karially',
      title: 'Karially.com',
      year: '2025',
      startDate: '2025-01',
      endDate: 'Present',
      description:
        'AI-powered career platform for resume generation, cover letters, and goal tracking.',
      highlights: [
        'AI resume & cover letter generation',
        'Personalized dashboard with recommendations',
        'Auth, persistence, and secure API integration',
      ],
      stack: ['Next.js', 'TypeScript', 'Tailwind', 'ShadCN', 'Node.js', 'AI APIs'],
      href: 'https://karially.com',
      status: 'live',
      accent: '#8b5cf6',
      emoji: '🤖',
      category: 'ai',
      sortOrder: 1,
    },
    {
      slug: 'studentia',
      title: 'StudentIA',
      year: '2024',
      startDate: '2024-03',
      endDate: '2024-08',
      description:
        'Dynamic admin dashboard with real-time charts and modular CRUD workflows.',
      highlights: [
        'Real-time data visualization with Chart.js',
        'Responsive modular layout',
        'Admin-focused UX patterns',
      ],
      stack: ['React', 'Chart.js', 'Tailwind CSS'],
      href: 'https://studentia.vercel.app',
      github: 'https://github.com/YEL-59/studentia',
      status: 'live',
      accent: '#22d3ee',
      emoji: '📊',
      category: 'dashboard',
      sortOrder: 2,
    },
    {
      slug: 'primeholiday',
      title: 'Primeholiday',
      year: '2024',
      description:
        'Holiday package explorer — browse, create, and manage travel experiences.',
      highlights: [
        'Server state with React Query',
        'Package listing & management flows',
        'Optimized data fetching patterns',
      ],
      stack: ['React', 'Tailwind CSS', 'React Query', 'Node.js'],
      href: 'https://primeholiday.vercel.app',
      github: 'https://github.com/YEL-59/primeholiday',
      status: 'live',
      accent: '#34d399',
      emoji: '✈️',
      category: 'platform',
      sortOrder: 3,
    },
    {
      slug: 'portfolio-bento',
      title: 'This Portfolio',
      year: '2025',
      description:
        'Mitchell Hou–inspired bento grid with physics skills, vault lock, and dotted map.',
      highlights: [
        'Matter.js draggable skill badges',
        'Paradox Engine passcode rituals',
        'Interactive dotted world map',
      ],
      stack: ['Next.js', 'TypeScript', 'Tailwind', 'Matter.js'],
      href: 'https://me-lilac-three.vercel.app',
      github: 'https://github.com/YEL-59/me',
      status: 'live',
      accent: '#f472b6',
      emoji: '🎨',
      category: 'portfolio',
      sortOrder: 4,
    },
    {
      slug: 'corona-kotha',
      title: 'Corona Kotha',
      year: '2021',
      description:
        'COVID-19 tracker covering 180+ countries with verified API integration.',
      highlights: [
        'Real-time global data',
        'Country-level filtering',
        'Open source on GitHub',
      ],
      stack: ['JavaScript', 'REST APIs', 'Chart.js'],
      github: 'https://github.com/YEL-59/corona-kotha',
      status: 'archived',
      accent: '#fb923c',
      emoji: '🦠',
      category: 'tool',
      sortOrder: 5,
    },
    {
      slug: 'softvence-clients',
      title: 'Softvence Client Work',
      year: '2024',
      description:
        'Production React apps for agency clients — conversion-focused UI and scalable architecture.',
      highlights: [
        'Multi-client component systems',
        'Performance & accessibility audits',
        'Redux Toolkit + React Query patterns',
      ],
      stack: ['React', 'TypeScript', 'Redux', 'Tailwind'],
      status: 'nda',
      accent: '#a78bfa',
      emoji: '🏢',
      category: 'platform',
      sortOrder: 6,
    },
    {
      slug: 'linkedin-clone',
      title: 'LinkedIn Clone',
      year: '2021',
      description:
        'Full-stack social feed clone with auth, posts, and responsive profile layouts.',
      highlights: [
        'Weekly build challenge',
        'Component-driven architecture',
        'REST API integration',
      ],
      stack: ['React', 'JavaScript', 'CSS'],
      href: 'https://linkedinclonev1.netlify.app/',
      github: 'https://github.com/YEL-59/linkend_clone',
      status: 'archived',
      accent: '#0ea5e9',
      emoji: '💼',
      category: 'platform',
      sortOrder: 7,
    },
    {
      slug: 'tofayel-vercel',
      title: 'tofayel.vercel.app',
      year: '2024',
      description:
        'Personal branding site with animated hero, project showcase, and download CV flow.',
      highlights: [
        'Animated UI & design system',
        'Project filtering',
        'Performance optimized',
      ],
      stack: ['Next.js', 'TypeScript', 'Tailwind'],
      href: 'https://tofayel.vercel.app',
      github: 'https://github.com/YEL-59/tofayel',
      status: 'live',
      accent: '#fbbf24',
      emoji: '⚡',
      category: 'portfolio',
      sortOrder: 8,
    },
    {
      slug: 'figtail',
      title: 'Figtail',
      year: '2025',
      description:
        'Tailwind CSS design system with reusable UI patterns and component recipes.',
      highlights: [
        'Design system documentation',
        'Reusable Tailwind patterns',
        'Open source component library',
      ],
      stack: ['JavaScript', 'Tailwind CSS', 'React'],
      href: 'https://figtail.vercel.app',
      github: 'https://github.com/YEL-59/figtail',
      status: 'live',
      accent: '#2dd4bf',
      emoji: '🎨',
      category: 'tool',
      sortOrder: 9,
    },
    {
      slug: 'react-cool-toast',
      title: 'React Cool Toast',
      year: '2025',
      description: 'Lightweight toast notification component for React apps.',
      highlights: [
        'TypeScript-first API',
        'Customizable animations',
        'Open source npm-ready component',
      ],
      stack: ['React', 'TypeScript'],
      github: 'https://github.com/YEL-59/react-cool-toast',
      status: 'live',
      accent: '#f87171',
      emoji: '🔔',
      category: 'tool',
      sortOrder: 10,
    },
  ],
  openSource: [
    {
      slug: 'gradient-button',
      name: 'Gradient Button',
      category: 'Button',
      description: 'Animated CTA with hover glow and loading state.',
      features: ['Variants', 'Loading', 'Icon slot', 'TypeScript props'],
      stack: ['React', 'TypeScript', 'Tailwind'],
      preview: 'button',
      accent: '#a78bfa',
      emoji: '🎯',
      github: 'https://github.com/YEL-59',
      sortOrder: 1,
    },
    {
      slug: 'glass-card',
      name: 'Glass Card',
      category: 'Card',
      description: 'Frosted glass bento card with theme-aware borders.',
      features: ['Dark/light', 'Hover lift', 'Slot API', 'Responsive'],
      stack: ['React', 'TypeScript', 'Tailwind'],
      preview: 'card',
      accent: '#22d3ee',
      emoji: '🧊',
      github: 'https://github.com/YEL-59',
      sortOrder: 2,
    },
    {
      slug: 'minimal-navbar',
      name: 'Minimal Navbar',
      category: 'Navbar',
      description: 'Sticky header with clock, theme toggle, and avatar.',
      features: ['Theme toggle', 'Live clock', 'Mobile ready', 'Accessible'],
      stack: ['Next.js', 'TypeScript', 'Tailwind'],
      preview: 'navbar',
      accent: '#34d399',
      emoji: '🧭',
      github: 'https://github.com/YEL-59',
      sortOrder: 3,
    },
    {
      slug: 'bento-footer',
      name: 'Bento Footer',
      category: 'Footer',
      description: 'Rounded footer bar with centered nav links.',
      features: ['Social links', 'Value pills', 'Rounded top', 'Responsive'],
      stack: ['React', 'TypeScript', 'Tailwind'],
      preview: 'footer',
      accent: '#fb923c',
      emoji: '👣',
      github: 'https://github.com/YEL-59',
      sortOrder: 4,
    },
    {
      slug: 'slash-breadcrumb',
      name: 'Slash Breadcrumb',
      category: 'Breadcrumb',
      description: 'Animated breadcrumb trail with page context.',
      features: ['Auto truncate', 'Keyboard nav', 'Custom separator', 'ARIA'],
      stack: ['React', 'TypeScript', 'Tailwind'],
      preview: 'breadcrumb',
      accent: '#f472b6',
      emoji: '🔗',
      github: 'https://github.com/YEL-59',
      sortOrder: 5,
    },
    {
      slug: 'hero-banner',
      name: 'Hero Banner',
      category: 'Banner',
      description: 'Gradient hero with badge, headline, and CTA row.',
      features: ['Gradient mesh', 'Badge slot', 'CTA group', 'Motion safe'],
      stack: ['React', 'TypeScript', 'Tailwind'],
      preview: 'banner',
      accent: '#fbbf24',
      emoji: '🚀',
      github: 'https://github.com/YEL-59',
      sortOrder: 6,
    },
  ],
  socialLinks: [
    {
      label: 'GitHub',
      href: 'https://github.com/YEL-59',
      platform: 'github',
      placement: 'vault',
      sortOrder: 1,
    },
    {
      label: 'LinkedIn',
      href: 'https://www.linkedin.com/in/tofayel-islam',
      platform: 'linkedin',
      placement: 'vault',
      sortOrder: 2,
    },
    {
      label: 'Live Site',
      href: 'https://tofayel.vercel.app/',
      platform: 'website',
      placement: 'vault',
      sortOrder: 3,
    },
    {
      label: 'Email',
      href: 'mailto:hello@tofayel.dev',
      platform: 'email',
      placement: 'footer',
      sortOrder: 1,
    },
    {
      label: 'Instagram',
      href: '#',
      platform: 'instagram',
      placement: 'footer',
      sortOrder: 2,
    },
    {
      label: 'LinkedIn',
      href: 'https://www.linkedin.com/in/tofayel-islam',
      platform: 'linkedin',
      placement: 'footer',
      sortOrder: 3,
    },
    {
      label: 'Github',
      href: 'https://github.com/YEL-59',
      platform: 'github',
      placement: 'footer',
      sortOrder: 4,
    },
    {
      label: 'Medium',
      href: '#',
      platform: 'medium',
      placement: 'footer',
      sortOrder: 5,
    },
  ],
  people: [
    {
      name: 'Miskat Showmik',
      relation: 'best friend',
      imageUrl: 'https://avatars.githubusercontent.com/u/77013640?v=4',
      bioParagraphs: [
        "Behind every good build is someone who tells you the truth. For me, that's Miskat Showmik — my best friend and one of the sharpest developers I know. We've grown up in the same Dhaka dev scene, swapped ideas over countless late nights, and pushed each other from student projects to real software.",
        'Miskat is a software developer focused on Python, machine learning, and clean engineering. He ships open source on GitHub, experiments with AI frameworks, and never lets me settle for "good enough" UI.',
      ],
      focusTags: ['Python', 'machine learning', 'open source'],
      links: [
        { label: 'GitHub', href: 'https://github.com/Miskat-UL' },
        { label: 'Portfolio', href: 'http://dev.miskatbyte.xyz/' },
        { label: 'Email', href: 'mailto:miskatshowmik@gmail.com' },
      ],
      sortOrder: 1,
    },
  ],
  files: [
    {
      name: 'More about me',
      type: 'doc',
      href: '/about',
      sortOrder: 1,
    },
    {
      name: 'Next.js Projects_2025',
      type: 'doc',
      href: '/project',
      sortOrder: 2,
    },
    {
      name: 'Project list',
      type: 'folder',
      href: '/project-list',
      description: 'Password-protected repo column',
      sortOrder: 3,
    },
    {
      name: 'Open Source',
      type: 'folder',
      href: '/opensource',
      sortOrder: 4,
    },
    {
      name: 'Resume',
      type: 'pdf',
      href: '/resume',
      downloadUrl: '/resume/tofayel-resume.pdf',
      sortOrder: 5,
    },
  ],
};
